### ISSUE TITLE
Players don't get the option to be revived once they die

### ISSUE THREAD

**Issue by justalemon** [TheTofuShop/Menu#41]
☁️ **What are you trying to do?**

Keep playing after I die.

⭐ **What do you expect to happen?**

My character is revived.

🐞 **What happens instead?**

It stays dead.

❓ **Is there something else that we need to know?**

I see two possible ways to fix this:

1. The player is revived as soon as it dies
2. The Spawn Menu is opened to respawn on a specific location

**Comment by justalemon** [comment]
You know what, let's make it configurable.

I prefer the option to select a location to spawn, but some people might prefer to be revived in the same place as before.

**Comment by mPrism** [comment]
I feel like the player should stay where they are after death, mostly because in cases where you're doing whatever you would need to do on foot, you wouldn't want to choose the map again to get back to what you're doing. if some troll hits you while you're /dv ing cars, it'll be easier to spawn on the same map you died on or the same spot. However do what you feel is necessary

**Comment by justalemon** [comment]
> let's make it configurable
That would be the best option. You don't like it? Change the setting, simple.

**Comment by mPrism** [comment]
Perfect

**Comment by justalemon** [comment]
Now you can select 3 different ways to respawn when you die:

* Wait and Respawn: Waits some time and then respawns the player in the same position (3 seconds by default, can be changed by staff)
* Respawn Instantly: You are respawned in the same location instantly after you die
* Use Spawn Menu: The spawn menu will be opened for you to spawn on a specific location
